name: gdnsd checkconf

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  checkconf-job:
    runs-on: ubuntu-24.04
    name: gdnsd checkconf
    steps:
      - uses: actions/checkout@v4
      - id: checkconf
        uses: miraheze/dns-check-action@v1
        with:
          geoip-directory: '/usr/share/GeoIP'
          geoip-filename: 'GeoLite2-Country.mmdb'
  notify-irc:
    needs: checkconf-job
    runs-on: ubuntu-latest
    if: ${{ always() && github.repository_owner == 'miraheze' && ( github.ref == 'refs/heads/master' || github.event_name == 'pull_request' ) }}
    steps:
      - name: succeeded
        uses: technote-space/workflow-conclusion-action@v3
      - uses: rectalogic/notify-irc@v2
        if: env.WORKFLOW_CONCLUSION == 'success'
        with:
          channel: "#miraheze-tech-ops"
          server: "irc.libera.chat"
          nickname: miraheze-github
          message: ${{ github.repository }} - ${{ github.actor }} the build passed.
          sasl_password: ${{ secrets.IRC_MIRAHEZEBOTS }}

      - name: failed
        uses: technote-space/workflow-conclusion-action@v3
      - uses: rectalogic/notify-irc@v2
        if: env.WORKFLOW_CONCLUSION == 'failure'
        with:
          channel: "#miraheze-tech-ops"
          server: "irc.libera.chat"
          nickname: miraheze-github
          message: ${{ github.repository }} - ${{ github.actor }} the build has errored.
          sasl_password: ${{ secrets.IRC_MIRAHEZEBOTS }}
